---
fail_fast: false

default_language_version:
  python: '3.12'

repos:
  - repo: local
    hooks:
      - id: check-bash-syntax
        name: Check Shell scripts syntax corectness
        language: system
        entry: bash -n
        files: \.sh$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-builtin-literals
      - id: check-yaml
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-toml
      - id: debug-statements
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: mixed-line-ending
        args:
          - --fix
          - lf
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: file-contents-sorter
        files: ^.*(\.env_dev|requirements\.in)$
      - id: no-commit-to-branch
  - repo: https://github.com/lyz-code/yamlfix
    rev: 1.17.0
    hooks:
      - id: yamlfix
        args:
          - --config-file
          - yamlfix.toml
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        entry: toml-sort
        files: \.toml$
        args:
          - -a
          - --in-place
          - --trailing-comma-inline-array
          - --spaces-indent-inline-array=4
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-workflows
        args:
          - --verbose
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|css|scss|less|html|markdown|md)$
        additional_dependencies:
          - prettier
          - prettier-plugin-css-order
          - postcss
          - prettier-plugin-tailwindcss
  - repo: git@github.com:cordada-io/pre-commit-hooks.git
    rev: 2024.10.29.2
    hooks:
      - id: debug-statements
      - id: enum-casing
      - id: schema-casing
      - id: alembic-comments
        files: src/database/migrations/versions
      - id: db-commit
        name: Allow db.commit() only on endpoints.py, views.py and tasks.py
        exclude: (\/tests\/|endpoints.py|views.py|tasks.py)
      - id: optional-str
        files: schemas.py
      - id: github-actions-timeout-minutes
        files: .github/workflows
      - id: github-self-hosted
        files: .github/workflows
      - id: github-actions-versions
        files: .github/workflows
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
      - id: ruff-format
  # TODO: Move to the pre-commit-hooks repo after the issue is fixed
  # https://github.com/PyCQA/docformatter/pull/287#issuecomment-2401028403
  - repo: local
    hooks:
      - id: docformatter
        name: docformatter
        description: Formats docstrings to follow PEP 257.
        entry: uvx --isolated docformatter
        args:
          - --in-place
        language: python
        types:
          - python
  - repo: local
    hooks:
      - id: mypy
        name: Check type hints with mypy
        language: system
        entry: uv run dmypy run
        pass_filenames: false
