fix = true
src = ["src"]
target-version = "py312"

[lint]
extend-select = ["FAST"]
ignore = ["E501", "N805", "N818", "PGH003", "RUF018"]
preview = true
select = ["ARG", "E", "ERA", "F", "FAST", "I", "N", "PGH", "RUF", "UP"]

[lint.flake8-quotes]
docstring-quotes = "single"

[lint.isort]
force-single-line = true
lines-after-imports = 2
