target-version = "py312"
fix = true
src = ["src"]

[lint]
select = ["E", "F", "N", "UP", "I", "PGH", "FAST", "RUF", "ERA", "ARG"]
extend-select = ["FAST"]
ignore = ["N805", "N818", "E501", "PGH003", "RUF018"]
preview = true

[lint.flake8-quotes]
docstring-quotes = "single"

[lint.isort]
force-single-line = true
lines-after-imports = 2
